services:
  sd_zoo_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${BUILD_ARCH}
    platform: ${BUILD_PLATFORM}
    container_name: sd-zoo-management-api
    image: sd.zoo.management
    restart: always
    env_file:
      - ./.env
    environment:
      # Dockerfile build optimization
      - DOTNET_EnableWriteXorExecute=0
      - DOTNET_NUGET_SIGNATURE_VERIFICATION=false
    ports:
      - ${SD_ZOO_API_PORT}:7070